spring:
  data:
    mongodb:
      uri: mongodb+srv://hiran9204:1234@cluster0.4sfue.mongodb.net/restaurant_db?retryWrites=true&w=majority&appName=Cluster0
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8081  # Avoid port conflicts with other services


cloudinary:
  cloud_name: dlhovnzmy
  api_key: 658539594264238
  api_secret: sGyAckY2ASo3WtKx3_e7f6ytORI